// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtvuWYqM6Nolmb9-dC0jyyMXb_kQoqEZ8',
    appId: '1:515191886662:web:2d5e5add11cebd6702cb47',
    messagingSenderId: '515191886662',
    projectId: 'mess-b73a8',
    authDomain: 'mess-b73a8.firebaseapp.com',
    databaseURL: 'https://mess-b73a8-default-rtdb.firebaseio.com',
    storageBucket: 'mess-b73a8.appspot.com',
    measurementId: 'G-D9WVWCLGFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJQivmNbHdfDJpyoliMwSn7G244vDvIRs',
    appId: '1:515191886662:android:7d0dcf016b20505602cb47',
    messagingSenderId: '515191886662',
    projectId: 'mess-b73a8',
    databaseURL: 'https://mess-b73a8-default-rtdb.firebaseio.com',
    storageBucket: 'mess-b73a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1bksmf6hVsXTfoO_FOtUDTby8tg0ch5w',
    appId: '1:515191886662:ios:d47330fad0aeced502cb47',
    messagingSenderId: '515191886662',
    projectId: 'mess-b73a8',
    databaseURL: 'https://mess-b73a8-default-rtdb.firebaseio.com',
    storageBucket: 'mess-b73a8.appspot.com',
    iosBundleId: 'com.example.assign7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1bksmf6hVsXTfoO_FOtUDTby8tg0ch5w',
    appId: '1:515191886662:ios:d47330fad0aeced502cb47',
    messagingSenderId: '515191886662',
    projectId: 'mess-b73a8',
    databaseURL: 'https://mess-b73a8-default-rtdb.firebaseio.com',
    storageBucket: 'mess-b73a8.appspot.com',
    iosBundleId: 'com.example.assign7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtvuWYqM6Nolmb9-dC0jyyMXb_kQoqEZ8',
    appId: '1:515191886662:web:929043c4efb575ef02cb47',
    messagingSenderId: '515191886662',
    projectId: 'mess-b73a8',
    authDomain: 'mess-b73a8.firebaseapp.com',
    databaseURL: 'https://mess-b73a8-default-rtdb.firebaseio.com',
    storageBucket: 'mess-b73a8.appspot.com',
    measurementId: 'G-B1JEXTG3TW',
  );
}
