// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr-wnZOqz7CP2Qlt5WYRtd9xY3KCd7lRA',
    appId: '1:21594271838:web:c7a1d9b4c2227a43ee84cf',
    messagingSenderId: '21594271838',
    projectId: 'final-f84ec',
    authDomain: 'final-f84ec.firebaseapp.com',
    storageBucket: 'final-f84ec.appspot.com',
    measurementId: 'G-X0R0BRM9T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNtTDfg3IWTiEh-URiyV9IE287tTrnGU',
    appId: '1:21594271838:android:27dc0c8cb6dabdb7ee84cf',
    messagingSenderId: '21594271838',
    projectId: 'final-f84ec',
    storageBucket: 'final-f84ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwKGw1WwTV1SyWDtfDQnLLdggqr4lpjQ',
    appId: '1:21594271838:ios:79a063d367c7a9d6ee84cf',
    messagingSenderId: '21594271838',
    projectId: 'final-f84ec',
    storageBucket: 'final-f84ec.appspot.com',
    iosBundleId: 'com.example.finalpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmwKGw1WwTV1SyWDtfDQnLLdggqr4lpjQ',
    appId: '1:21594271838:ios:79a063d367c7a9d6ee84cf',
    messagingSenderId: '21594271838',
    projectId: 'final-f84ec',
    storageBucket: 'final-f84ec.appspot.com',
    iosBundleId: 'com.example.finalpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr-wnZOqz7CP2Qlt5WYRtd9xY3KCd7lRA',
    appId: '1:21594271838:web:cbc103e57657dd23ee84cf',
    messagingSenderId: '21594271838',
    projectId: 'final-f84ec',
    authDomain: 'final-f84ec.firebaseapp.com',
    storageBucket: 'final-f84ec.appspot.com',
    measurementId: 'G-3G31MJNVW6',
  );
}
